#!/bin/bash

if [ "$(whoami)" != "root" ] && [[ "$(whoami)" != *"u0"* ]]; then
    echo "Failed to execute: root permission needed"
    exit
fi

if [ $# -eq 0 ]; then
    printf "Usage: beach <command>\n\tedit\t\tEdit source code\n\tfetchstickerid\tStart Sticker ID Fetcher\n\tremove\t\tRemove Tyfe from the machine\n\tresettoken\tReset all token cache\n\tsidfedit\tEdit Sticker ID Fetcher source code\n\tstart\t\tStart Tyfe\n\tupdate\t\tUpdate Tyfe to the latest version\n\tversion\t\tPrint the current version\n\n"
    exit
fi

if [ "$1" = "edit" ]; then
    nano /etc/beach-noxt/line.py
    exit
fi

if [ "$1" = "remove" ]; then
    echo "Removing..."
    rm -rf /etc/beach-noxt/
    rm /usr/bin/beach-noxt
    printf "Done!\n\n"
    exit
fi

if [ "$1" = "resettoken" ]; then
    echo "Resetting.."
    cd /etc/beach/
    python3 line.py "reset"
    printf "Done!\n\n"
    exit
fi

if [ "$1" = "start" ]; then
    cd /etc/beach-noxt/
    python3 line.py
    exit
fi

if [ "$1" = "update" ]; then
    echo "Updating By beach..."
    cd /tmp/
    git clone https://gitlab.com/beach-noxtian-01/beach-noxt &> /dev/null
    noxtian/install.sh
    rm -rf /tmp/noxtina
    exit
fi

echo "Failed to execute: Unknown command"
